# Generated by Django 4.2.7 on 2024-04-13 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(default=0, unique=True, verbose_name='порядковый номер')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(default='ваше описание модуля', verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='картинка')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('last_update', models.DateField(auto_now=True, verbose_name='последнее обновление')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
    ]
