# Generated by Django 4.2.7 on 2024-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('serial_number',), 'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
        migrations.AddField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
    ]
