# Generated by Django 4.2.7 on 2024-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_options_module_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
