# Generated by Django 4.2.7 on 2024-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='количество лайков'),
        ),
    ]
